# Generated by Django 2.1.12 on 2019-10-10 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20190919_1029'),
    ]

    operations = [
        migrations.AddField(
            model_name='ncf_dd_audit_log',
            name='da_effective_date_set',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
