# Generated by Django 2.1.12 on 2019-10-10 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_ncf_dd_audit_log_da_effective_date_set'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ncf_dd_audit_log',
            old_name='da_effective_date_set',
            new_name='da_reporting_date_set',
        ),
        migrations.AddField(
            model_name='ncf_dd_audit_log',
            name='da_reporting_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
