# Generated by Django 2.1.12 on 2019-10-11 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_database_joblog'),
    ]

    operations = [
        migrations.AddField(
            model_name='ncf_datacash_drawdowns',
            name='dd_in_arrears_app',
            field=models.BooleanField(default=False),
        ),
    ]
