# Generated by Django 2.1.12 on 2019-10-14 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_ncf_datacash_drawdowns_dd_in_arrears_app'),
    ]

    operations = [
        migrations.AddField(
            model_name='ncf_datacash_drawdowns',
            name='dd_arrears_flag',
            field=models.BooleanField(default=False),
        ),
    ]
