# Generated by Django 2.1.12 on 2019-10-15 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_ncf_datacash_drawdowns_dd_arrears_flag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='go_extensions',
            name='ap_extension_last_interface_run',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='go_extensions',
            name='ap_extension_next_interface_run',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
