# Generated by Django 2.1.12 on 2019-10-21 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_arrears', '0010_auto_20191016_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent_allocations_control',
            name='aac_agent_phase',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
