# Generated by Django 2.1.12 on 2019-10-16 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_arrears', '0009_agent_allocations_control'),
    ]

    operations = [
        migrations.AddField(
            model_name='arrears_summary_agreement_level',
            name='arr_unallocated_last_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='arrears_summary_agreement_level',
            name='arr_unallocated_value_grossofvat',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='arrears_summary_agreement_level',
            name='arr_unallocated_value_netofvat',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
    ]
