# Generated by Django 2.1.12 on 2019-11-19 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_agreement_crud', '0027_auto_20191004_0816'),
    ]

    operations = [
        migrations.CreateModel(
            name='agreement_number_validation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.CharField(blank=True, max_length=50, null=True)),
                ('agreement_type', models.IntegerField(blank=True, null=True)),
                ('funder', models.IntegerField(blank=True, null=True)),
                ('broker', models.IntegerField(blank=True, null=True)),
                ('prepend', models.CharField(blank=True, max_length=50, null=True)),
                ('append', models.CharField(blank=True, max_length=50, null=True)),
                ('min_length', models.IntegerField(blank=True, null=True)),
                ('max_length', models.IntegerField(blank=True, null=True)),
                ('allow_digits', models.NullBooleanField(default=True)),
                ('allow_letters', models.NullBooleanField(default=True)),
                ('allow_characters', models.NullBooleanField(default=True)),
                ('disallowed_characters', models.CharField(blank=True, max_length=50, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='go_collection_schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection_schedule', models.SmallIntegerField(blank=True, null=True)),
                ('collection_description', models.CharField(blank=True, max_length=50, null=True)),
                ('selectable', models.NullBooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='go_selectable_functionality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('function', models.CharField(blank=True, max_length=50, null=True)),
                ('customer', models.CharField(blank=True, max_length=50, null=True)),
                ('agreement_type', models.IntegerField(blank=True, null=True)),
                ('funder', models.IntegerField(blank=True, null=True)),
                ('broker', models.IntegerField(blank=True, null=True)),
                ('option1', models.IntegerField(blank=True, null=True)),
                ('option2', models.IntegerField(blank=True, null=True)),
                ('selectable', models.IntegerField(blank=True, null=True)),
                ('visible', models.IntegerField(blank=True, null=True)),
                ('selectable_value', models.IntegerField(blank=True, null=True)),
                ('hidden_value', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='go_agreement_index',
            name='doc_flag',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
