# Generated by Django 2.1.12 on 2019-11-20 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_agreement_crud', '0030_auto_20191119_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='go_account_transaction_detail',
            name='transactionpaymentmethod',
            field=models.CharField(default='', max_length=15, null=True),
        ),
    ]
