# Generated by Django 2.1.12 on 2019-11-21 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_agreement_crud', '0031_go_account_transaction_detail_transactionpaymentmethod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='go_agreement_id_definitions',
            name='profile_type',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
