# Generated by Django 2.1.12 on 2019-11-21 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core_agreement_crud', '0032_auto_20191121_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='go_agreement_id_definitions',
            name='profile_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core_agreement_crud.go_profile_types'),
        ),
    ]
