# Generated by Django 2.1.12 on 2019-11-22 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core_agreement_crud', '0033_auto_20191121_1113'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='go_agreement_index',
            name='profile',
        ),
        migrations.AddField(
            model_name='go_agreement_index',
            name='agreenent_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core_agreement_crud.go_agreement_definitions'),
        ),
    ]
