# Generated by Django 2.1.12 on 2019-11-22 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_agreement_crud', '0034_auto_20191122_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='go_agreement_index',
            name='agreenent_type',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
