# Generated by Django 2.1.12 on 2019-11-22 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_agreement_crud', '0035_auto_20191122_1412'),
    ]

    operations = [
        migrations.RenameField(
            model_name='go_agreement_index',
            old_name='agreenent_type',
            new_name='agreement_type',
        ),
    ]
