# Generated by Django 2.1.12 on 2019-11-22 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core_agreement_crud', '0036_auto_20191122_1418'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='go_agreement_index',
            name='agreement_type',
        ),
        migrations.AddField(
            model_name='go_agreement_index',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core_agreement_crud.go_profile_types'),
        ),
    ]
