# Generated by Django 2.1.12 on 2019-11-27 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_agreement_crud', '0037_auto_20191122_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='go_account_transaction_detail',
            name='transaction_detail_unique',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='go_account_transaction_summary',
            name='transaction_summary_unique',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
