# Generated by Django 2.1.12 on 2019-10-18 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_direct_debits', '0003_ddhistory_provider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ddhistory',
            name='effective_date',
            field=models.DateTimeField(db_column='effective_date', null=True),
        ),
    ]
